//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DL
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class ESantiagoCajeroEntities : DbContext
    {
        public ESantiagoCajeroEntities()
            : base("name=ESantiagoCajeroEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Retiro> Retiros { get; set; }
        public virtual DbSet<SaldoCajero> SaldoCajeroes { get; set; }
    
        public virtual int RealizarRetiro(Nullable<int> billetes1000, Nullable<int> billetes500, Nullable<int> billetes200, Nullable<int> billetes100, Nullable<int> billetes50, Nullable<int> billetes20)
        {
            var billetes1000Parameter = billetes1000.HasValue ?
                new ObjectParameter("Billetes1000", billetes1000) :
                new ObjectParameter("Billetes1000", typeof(int));
    
            var billetes500Parameter = billetes500.HasValue ?
                new ObjectParameter("Billetes500", billetes500) :
                new ObjectParameter("Billetes500", typeof(int));
    
            var billetes200Parameter = billetes200.HasValue ?
                new ObjectParameter("Billetes200", billetes200) :
                new ObjectParameter("Billetes200", typeof(int));
    
            var billetes100Parameter = billetes100.HasValue ?
                new ObjectParameter("Billetes100", billetes100) :
                new ObjectParameter("Billetes100", typeof(int));
    
            var billetes50Parameter = billetes50.HasValue ?
                new ObjectParameter("Billetes50", billetes50) :
                new ObjectParameter("Billetes50", typeof(int));
    
            var billetes20Parameter = billetes20.HasValue ?
                new ObjectParameter("Billetes20", billetes20) :
                new ObjectParameter("Billetes20", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("RealizarRetiro", billetes1000Parameter, billetes500Parameter, billetes200Parameter, billetes100Parameter, billetes50Parameter, billetes20Parameter);
        }
    
        public virtual ObjectResult<CajeroGetSaldo_Result> CajeroGetSaldo()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<CajeroGetSaldo_Result>("CajeroGetSaldo");
        }
    
        public virtual ObjectResult<RetiroGetAll_Result> RetiroGetAll()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<RetiroGetAll_Result>("RetiroGetAll");
        }
    }
}
